travis:
  secure:
    BINSTAR_TOKEN: lds0BWvzcjQz3cBQjohV+GbRNXU7L87OxEeh1xr1t9i5EHBgem9YRU1fb39Qiewp4f1rA6ZsuuSPna1fzId0R4dwpNjS/yioPX+KYRjUKwR331zhXj/MtbwcKN7EQpaBr06AL/RHworrSrX2jOWqpESMR7KxcThJr7L9AoAp0Knau8o8NgDRuSucPkVO8MUelzwiJIFvvJkfocu4iqT+B96d3UzKzFtErgG/lmcXmQg2u5VZmSHSfbHwTFtMjxf0+mMnTKpK+NiKYmv5aLJ9EIBcMnEkP4vvh4THQzJrdrz5lI9FsjdoUq/tOEVnG7An8+RFBawHim4olAMoFU8VBYRmtZNOGWGehYjvR/4SPNGTaO0BaTC2l6j1ybf5umlOskBPDQ2puveYU0g//TdU98duJSpxbEhExlfwe1bj8e3ajE0QvZq7wsmJfUwoa4PnD0wUe8hth8yjbnFHdXRsCLxUQR+LxvgA041uXn8ZcgcGX+XHjahob3sgna86bNlBXdbhZ/662M0odFw6Z/Io58y/hESdbbziznR9deQvRmn5owWL/2WHUeg/MLS6xvd8OSSmlROwZIqFKt/KizVoF8/xciQO6Txds5ujLAxMwlv2ATpgfeDIJQZFhOVlyBgiqmY9A8VqbJgDq/L/uCe6PWS2E7b/LeRx4px6P7g4rwA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
